version: '3.8'

services:
  prompttune:
    build: .
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./app.py:/app/app.py
      - ./sample_data:/app/sample_data
    restart: unless-stopped
